---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(lubridate)
library(GGally)
library(ggfortify)
library(leaps)
library(glmulti)
library(modelr)
```

```{r}
avocado <- read_csv("data/avocado.csv") %>% 
  janitor::clean_names()
avocado_dict <- read_csv("data/data_dict.txt")
```

```{r}
avocado %>% 
  summarise(across(.cols = everything(), 
                   .fns = ~sum(is.na(.x))))
```

```{r}
avocado_season <- avocado %>% 
  mutate(season = case_when(
    month(date) %in% c(3:5) ~ "spring",
    month(date) %in% c(6:8) ~ "summer",
    month(date) %in% c(9:11) ~ "autumn",
    TRUE ~ "winter"
  ))
```

```{r}
avocado_tidy <- avocado_season %>% 
  select(-x1, -date, -region) %>% 
  mutate(type = as.factor(type),
         year = as.factor(year),
         season = as.factor(season))
```

# EXHAUSTIVE

```{r}
regsubsets <- regsubsets(average_price ~ ., 
                                    data = avocado_tidy,
                                    nvmax = 11, 
                                    method = "exhaustive")
sum_regsubsets <- summary(regsubsets)
```

```{r}
plot(regsubsets, scale = "adjr2")
plot(regsubsets, scale = "bic")
```

```{r}
plot(sum_regsubsets$rsq, type = "b")
plot(sum_regsubsets$bic, type = "b")
```

```{r}
sum_regsubsets$which[11,]
```

## CHECK TYPE

```{r}
test_m <- lm(average_price ~ total_volume + x4225 + small_bags + x_large_bags,
             data = avocado_tidy)

type_m <- lm(average_price ~ total_volume + x4225 + small_bags + x_large_bags +
               type,
             data = avocado_tidy)
```

```{r}
anova(null_m, type_m)
```

-> Keep type

## CHECK YEAR

```{r}
year_m <- lm(average_price ~ total_volume + x4225 + small_bags + x_large_bags +
               type + year,
             data = avocado_tidy)
```

```{r}
anova(type_m, year_m)
```

-> Keep year

## CHECK SEASON

```{r}
season_m <- lm(average_price ~ total_volume + x4225 + small_bags + x_large_bags 
               + type + year + season,
             data = avocado_tidy)
```

```{r}
anova(year_m, season_m)
```

-> Keep season

```{r}
summary(season_m)
autoplot(season_m)
```

# GLMULTI

```{r}
glmulti_fit <- glmulti(average_price ~.,
                       data = avocado_tidy,
                       level = 2,
                       minsize = 0,
                       max_size = -1,
                       marginality = TRUE,
                       method = "g",
                       crit = bic,
                       plotty = FALSE,
                       report = TRUE,
                       confsetsize = 10,
                       fitfunction = lm)
```

```{r}
mod_interact <- lm(average_price ~ type + year + season + total_volume + x4046 + 
                     x4225 + x4770 + total_bags + small_bags + large_bags + 
                     x_large_bags + year:type + season:type + season:year + 
                     x4225:total_volume + x4225:x4046 + x4770:total_volume + 
                     x4770:x4225 + large_bags:small_bags + x_large_bags:x4046 + 
                     x_large_bags:large_bags + type:total_volume + type:x4046 + 
                     type:x4225 + type:total_bags + type:small_bags + 
                     type:large_bags + type:x_large_bags + year:x4225 + 
                     year:small_bags + year:x_large_bags,
                   data = avocado_tidy)
summary(mod_interact)
autoplot(mod_interact)
```

```{r}
summary(season_m)$adj.r.squared
summary(mod_interact)$adj.r.squared
```

```{r}
BIC(season_m)
BIC(mod_interact)
```

# TESTING

```{r}
n_data <- nrow(avocado_tidy)

test_index <- sample(1:n_data, size = n_data*0.2)

test <- slice(avocado_tidy, test_index)
train <- slice(avocado_tidy, -test_index)
```

```{r}
train_mod_e <- lm(average_price ~ total_volume + x4225 + small_bags + x_large_bags 
               + type + year + season,
             data = train)

train_mod_i <- lm(average_price ~ type + year + season + total_volume + x4046 + 
                     x4225 + x4770 + total_bags + small_bags + large_bags + 
                     x_large_bags + year:type + season:type + season:year + 
                     x4225:total_volume + x4225:x4046 + x4770:total_volume + 
                     x4770:x4225 + large_bags:small_bags + x_large_bags:x4046 + 
                     x_large_bags:large_bags + type:total_volume + type:x4046 + 
                     type:x4225 + type:total_bags + type:small_bags + 
                     type:large_bags + type:x_large_bags + year:x4225 + 
                     year:small_bags + year:x_large_bags,
                   data = train)
```

```{r}
pred_test_e <- test %>% 
  add_predictions(train_mod_e) %>% 
  select(average_price, pred)

pred_test_i <- test %>% 
  add_predictions(train_mod_i) %>% 
  select(average_price, pred)
```

```{r}
mse_test_e <- mean((pred_test_e$pred - test$average_price)^2)
mse_test_i <- mean((pred_test_i$pred - test$average_price)^2)

mse_test_e
mse_test_i
```

